package com.hiczp.bilibili.live.danmuji.ui;

import com.hiczp.bilibili.live.danmu.api.LiveDanMuSender;
import com.hiczp.bilibili.live.danmuji.Config;
import com.hiczp.bilibili.live.danmuji.DanMuJi;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

/**
 * Created by czp on 17-6-21.
 */
public class LoginForm extends JFrame {
    private JPanel loginFormJPanel;
    private JTextArea cookiesTextArea;
    private JButton OKButton;
    private JButton testButton;

    private Config config = DanMuJi.getConfig();

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public LoginForm() {
        loadData();

        //监听器
        OKButton.addActionListener(actionEvent -> {
            saveData();
            dispose();
        });

        testButton.addActionListener(actionEvent -> {
            try {
                boolean isValid = LiveDanMuSender.testLogin(cookiesTextArea.getText());
                if (isValid) {
                    JOptionPane.showMessageDialog(this, "Cookies valid!");
                } else {
                    JOptionPane.showMessageDialog(this, "Cookies not correct!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, String.format("Error! %s: %s", e.getClass().getName(), e.getMessage()));
                e.printStackTrace();
            }
        });

        setTitle("LoginForm");
        setContentPane(loginFormJPanel);
        setLocationRelativeTo(null);
        pack();
        setVisible(true);
    }

    private void loadData() {
        cookiesTextArea.setText(config.cookies);
    }

    private void saveData() {
        config.cookies = cookiesTextArea.getText().replace("\n", "");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginFormJPanel = new JPanel();
        loginFormJPanel.setLayout(new GridLayoutManager(4, 4, new Insets(5, 5, 5, 5), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Cookies:");
        loginFormJPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("PS2: Only support login by cookies yet.");
        loginFormJPanel.add(label2, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("PS1: Cookies must include 'DedeUserID', 'DedeUserID__ckMd5', 'SESSDATA'.");
        loginFormJPanel.add(label3, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        OKButton = new JButton();
        OKButton.setText("OK");
        loginFormJPanel.add(OKButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        loginFormJPanel.add(scrollPane1, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 100), null, 0, false));
        cookiesTextArea = new JTextArea();
        cookiesTextArea.setLineWrap(true);
        scrollPane1.setViewportView(cookiesTextArea);
        testButton = new JButton();
        testButton.setText("Test");
        loginFormJPanel.add(testButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        loginFormJPanel.add(spacer1, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginFormJPanel;
    }
}
